import torch
import torch.nn as nn
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from scipy.stats import qmc
import numpy as np
from fipy import CellVariable, Grid1D, Grid2D
from fipy import Grid3D, TransientTerm, DiffusionTerm
import matplotlib.cm as cm


class PINN(nn.Module):
    """
    The PINN architecture.

    Parameters
    ----------
    n_neurons:int
    Number of neurons
    dim:int
    The number of spatial dimensions in which the equation is set (0<dim<4).
    hidden (nn.Sequential)
    The neural network architecture itself, which is
    composed by its 4 layers and their Tanh activation functions.
    """

    def __init__(self, n_neurons: int = 50, dim: int = 1):
        super(PINN, self).__init__()
        self.hidden = nn.Sequential(
            nn.Linear(dim+1, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, 1)
        )

    def forward(self, *coordinates: torch.Tensor,
                t: torch.Tensor) -> torch.Tensor:
        """
        The core method of the PINN, which approximates u(vec(x),t),
        where vec(x) means the spatial coordinates.

        Parameters
        ----------
        *coordinates:torch.Tensor
            The spatial coordinates (0<dim<4).
        t:torch.Tensor
            The temporal coordinates.

        Returns
        -------
        u: torch.Tensor
            the approximation of u(vec(x),t).
        """

        # concatenate the inputs
        inputs = torch.cat(coordinates + (t,), dim=1)
        pinn = self.hidden(inputs)
        return pinn


def lhs_sample_generator(n_points: int,
                         dim: int) -> tuple[torch.Tensor, ...]:
    """
    The latin hypercube sample point generator,
    based on the Quasi-Monte Carlo scipy submodel.

    Parameters
    ----------
    n_point:int
        The number of points generated by the function
    dim:int
        The dimension of the spatial coordinates plus one (1<dim<5).
        For example if the imput was 4 you would generate x, y, z, t,
        following classical cartesian nomenclature.

    Returns
    -------
    tuple[torch.Tensor, ...]
        A tuple of tensors of size dim
    """
    # create the points
    sampler = qmc.LatinHypercube(d=dim, seed=42)
    lhs_samples = sampler.random(n_points)

    # make them usable, first a tensor then an easily unpackable tuple
    lhs_samples = torch.Tensor(lhs_samples)
    lhs_samples.requires_grad = True
    lhs_samples_tuple = tuple(
        (lhs_samples[:, i].view(-1, 1)) for i in range(dim))

    return lhs_samples_tuple


def pde_residual(*coordinates: torch.Tensor,
                 t: torch.Tensor, model: nn.Module,
                 D: float = 0.01, R: float = 1) -> torch.Tensor:
    """
    Calculates the residual of the KPP-Fisher equation,
    inferring the dimension by the size of coordinates.

    Parameters
    ----------
    *coordinates:torch.Tensor
        The spatial coordinates (0<dim<4).
    t:torch.Tensor
        The temporal coordinates
    D:float=0.01
        The diffusion coefficient
    R:float=1
        The reaction rate

    Returns
    -------
    residual:torch.Tensor
        The residual of the KPP-Fisher equation
    """

    u = model(*coordinates, t=t)

    # temporal derivative
    du_dt = torch.autograd.grad(u, t, torch.ones_like(
        u), create_graph=True)[0]

    # compute the laplacian
    laplacian = 0
    for coord in coordinates:
        # first derivative
        du_dcoord = torch.autograd.grad(
            u, coord, create_graph=True, grad_outputs=torch.ones_like(u))[0]
        # second derivative
        d2u_dcoord2 = torch.autograd.grad(
            du_dcoord, coord, create_graph=True,
            grad_outputs=torch.ones_like(du_dcoord))[0]

        laplacian += d2u_dcoord2

    # kpp-fisher residual
    residual = du_dt-D*(laplacian)-R*u*(1-u)
    return residual


def neumann_condition(*coordinates: torch.Tensor,
                      t: torch.Tensor, model: nn.Module) -> float:
    """
    Computes the Neumann condition loss.

    Parameters
    ----------
    *coordinates: torch.Tensor
    The spatial coordinates.
    t: torch.Tensor
    The temporal coordinates.
    model: nn.Module
    The PINN.

    Returns
    -------
    loss: float
    The Neumann condition loss.
    """
    loss = 0.0
    # compute the first derivative and sum it to the loss
    for i, coord in enumerate(coordinates):
        for boundary_val in (0.0, 1.0):
            boundary_coords = list(coordinates)
            boundary_coords[i] = torch.full_like(coord, boundary_val,
                                                 requires_grad=True)

            u_b = model(*boundary_coords, t=t)
            du_dcoord = torch.autograd.grad(
                u_b, boundary_coords[i], create_graph=True,
                grad_outputs=torch.ones_like(u_b))[0]
            loss += torch.mean(du_dcoord**2)
    return loss


def dirichlet_condition(*coordinates: torch.Tensor,
                        t: torch.Tensor, model: nn.Module,
                        value_x0: float = 0.0,
                        value_x1: float = 0.0,
                        value_y0: float = 0.0, value_y1: float = 0.0,
                        value_z0: float = 0.0,
                        value_z1: float = 0.0) -> float:
    """
    Compute the dirichlet conditions loss

    Parameters
    ----------
    *coordinates: torch.Tensor
    The spatial coordinates.
    t: torch.Tensor
    The temporal coordinates.
    model: nn.Module
    The PINN.
    value_x0: float
    The dirichlet condition for x=0
    value_x1: float
    The dirichlet condition for x=1
    value_y0: float
    The dirichlet condition for y=0
    value_y1: float
    The dirichlet condition for y=1
    value_z0: float
    The dirichlet condition for z=0
    value_z1: float
    The dirichlet condition for z=1
    value_t0: float
    The initial condition

    Returns
    -------
    loss: float
    The Dirichlet condition loss.
    """
    loss = 0.0

    # create a matrix for the boundary conditions so that
    # u_ex_matrix[i][0]=value_i0 etc
    u_ex_matrix = [[value_x0, value_x1],
                   [value_y0, value_y1],
                   [value_z0, value_z1]]

    # compute the loss
    for i, coord in enumerate(coordinates):
        for boundary_index, boundary_val in enumerate((0.0, 1.0)):
            boundary_coords = list(coordinates)
            boundary_coords[i] = torch.full_like(coord, boundary_val,
                                                 requires_grad=True)

            u_pr = model(*boundary_coords, t=t)
            u_ex = u_ex_matrix[i][boundary_index]
            loss += torch.mean((u_pr-u_ex)**2)
    return loss


def loss_function(*coordinates: torch.Tensor, mode: str = "dirichlet",
                  t: torch.Tensor,
                  model: nn.Module, value_x0: float = 0.0,
                  value_x1: float = 0.0,
                  value_y0: float = 0.0, value_y1: float = 0.0,
                  value_z0: float = 0.0,
                  value_z1: float = 0.0,
                  value_t0: float = 0.0) -> float:
    """
    Computes the loss function as the sum of the initial conditions loss,
    boundary conditions loss and the residual loss.

    Parameters
    ----------
    *coordinates:torch.Tensor
        The spatial coordinates (0<dim<4).
    mode: str = "dirichlet"
        The type of boundary conditions applied.
    t:torch.Tensor
        The temporal coordinates
    model:nn.Module
        The approximated u(vec(x), t)
    value_x0: float
    The dirichlet condition for x=0
    value_x1: float
    The dirichlet condition for x=1
    value_y0: float
    The dirichlet condition for y=0
    value_y1: float
    The dirichlet condition for y=1
    value_z0: float
    The dirichlet condition for z=0
    value_z1: float
    The dirichlet condition for z=1
    value_t0: float
    The initial condition

    Returns
    -------
    loss:float
        The loss function numerical result.
    """

    # initial condition loss
    u_pr = model(*coordinates, t=torch.zeros_like(t))
    if mode == 'exact':
        u_ex = exact_solution_1D(
            coordinates[0], torch.zeros_like(coordinates[0]))
    else:
        u_ex = torch.full_like(t, value_t0)
    loss_ic = torch.mean((u_pr-u_ex)**2)

    # boundary conditions loss
    if mode == 'neumann':
        loss_bc = neumann_condition(*coordinates, t=t, model=model)
    elif mode == 'exact':
        u_0_pr = model(torch.zeros_like(t), t=t)
        u_1_pr = model(torch.full_like(t, 1), t=t)
        u_0_ex = exact_solution_1D(torch.zeros_like(t), t=t)
        u_1_ex = exact_solution_1D(torch.full_like(t, 1), t=t)

        loss_bc = torch.mean((u_0_pr - u_0_ex)**2) + \
            torch.mean((u_1_ex-u_1_pr)**2)
    elif mode == 'dirichlet':
        loss_bc = dirichlet_condition(*coordinates, t=t,
                                      model=model, value_x0=value_x0,
                                      value_x1=value_x1,
                                      value_y0=value_y0,
                                      value_y1=value_y1,
                                      value_z0=value_z0,
                                      value_z1=value_z1)
    else:
        raise (NameError('Invalid mode'))

    # residual loss
    loss_pde = torch.mean(pde_residual(*coordinates, t=t, model=model)**2)

    # total loss
    loss = loss_bc+loss_ic+loss_pde

    return loss


def exact_solution_1D(x: torch.Tensor,
                      t: torch.Tensor,
                      D: float = 0.01,
                      R: float = 1) -> torch.Tensor:
    """
    Calculates the exact solution of the KPP-Fisher equation.

    Parameters
    ----------
    x:torch.Tensor
        The spatial coordinates
    t:torch.Tensor
        The temporal coordinates
    D:float=0.01
        The diffusion coefficient
    R:float=1
        The reaction rate

    Returns
    -------
    exact_solution:torch.Tensor
        The exact solution of the KPP-Fisher equation in 1D
    """

    exponent = ((R/(6*D))**0.5)*x-5*R*t/6
    exp = torch.exp(exponent)
    exact_solution = (1+exp)**(-2)
    return exact_solution


def training_loop(n_epochs: int, n_neurons: int,
                  n_points: int, dim: int, mode: str,
                  value_x0: float, value_x1: float,
                  value_y0: float, value_y1: float, value_z0: float,
                  value_z1: float,
                  value_t0: float) -> tuple[nn.Module, list]:
    """
    Runs n_epochs loops to train the model.

    Parameters
    ----------
    n_epochs:int
    The number of epochs for the training loop.
    n_neurons:int
    The numer of neurons per layer.
    n_points:int
    The number of points for LHS sampling.
    dim:int
    The spatial dimensions.
    mode: str
    The type of boundary conditions.
    value_x0: float
    The dirichlet condition for x=0
    value_x1: float
    The dirichlet condition for x=1
    value_y0: float
    The dirichlet condition for y=0
    value_y1: float
    The dirichlet condition for y=1
    value_z0: float
    The dirichlet condition for z=0
    value_z1: float
    The dirichlet condition for z=1
    value_t0: float
    The initial condition

    Returns
    -------
    model:nn.Module
    The trained PINN.
    loss_list:list
    A list containing the loss every 10 epochs.
    """

    model = PINN(n_neurons, dim)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # reinitialize the model parameters
    model.apply(lambda m: m.reset_parameters()
                if hasattr(m, 'reset_parameters') else None)

    # sample point generation
    all_samples = lhs_sample_generator(n_points, dim+1)
    spatial_coords = all_samples[:-1]
    t = all_samples[-1]

    loss_list = []

    for epoch in range(n_epochs):
        model.train()

        loss = loss_function(*spatial_coords, t=t, model=model, mode=mode,
                             value_x0=value_x0, value_x1=value_x1,
                             value_y0=value_y0, value_y1=value_y1,
                             value_z0=value_z0, value_z1=value_z1,
                             value_t0=value_t0)

        # collect loss for loss evolution
        if epoch % 10 == 0:
            loss_list.append([loss.item(), epoch])

        # backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    return model, loss_list


def solve_with_fipy(dim: int, mode: str, value_x0: float, value_x1: float,
                    value_y0: float, value_y1: float, value_z0: float,
                    value_z1: float,
                    value_t0: float) -> list:
    """
    Solves the equation with fipy with
    dirichlet boundary conditions.

    Parameters
    ----------
    dim:int
    The number of spatial dimensions taken into consideration (0<dim<4)
    mode: str
    The type of boundary conditions applied.
    value_x0: float
    The dirichlet condition for x=0
    value_x1: float
    The dirichlet condition for x=1
    value_y0: float
    The dirichlet condition for y=0
    value_y1: float
    The dirichlet condition for y=1
    value_z0: float
    The dirichlet condition for z=0
    value_z1: float
    The dirichlet condition for z=1
    value_t0: float
    The initial condition

    Returns
    -------
    history:list
    A list containing u(vec(x), t) for 20^(dim+1) data points
    """

    nx = 20
    ny = nx
    nz = nx
    dx = 0.05
    dy = dx
    dz = dx

    if dim == 1:
        mesh = Grid1D(dx=dx, nx=nx)
    if dim == 2:
        mesh = Grid2D(dx=dx, dy=dy, nx=nx, ny=ny)
    if dim == 3:
        mesh = Grid3D(dx=dx, dy=dy, dz=dz, nx=nx, ny=ny, nz=nz)

    phi = CellVariable(name='solution variable', mesh=mesh, value=value_t0)

    # define kpp-fisher
    eq = TransientTerm() == DiffusionTerm(coeff=0.01) + phi*(1-phi)

    # set boundary conditions
    if mode == 'dirichlet':
        if dim == 1:
            phi.constrain(value_x0, where=mesh.facesLeft)
            phi.constrain(value_x1, where=mesh.facesRight)
        if dim == 2:
            phi.constrain(value_y0, where=mesh.facesBottom)
            phi.constrain(value_y1, where=mesh.facesTop)
        if dim == 3:
            phi.constrain(value_z0, where=mesh.facesFront)
            phi.constrain(value_z1, where=mesh.facesBack)

    elif mode == 'neumann':
        if dim == 1:
            phi.faceGrad.constrain(0.0, where=mesh.facesLeft)
            phi.faceGrad.constrain(0.0, where=mesh.facesRight)

        if dim == 2:
            phi.faceGrad.constrain(0.0, where=mesh.facesBottom)
            phi.faceGrad.constrain(0.0, where=mesh.facesTop)

        if dim == 3:
            phi.faceGrad.constrain(0.0, where=mesh.facesFront)
            phi.faceGrad.constrain(0.0, where=mesh.facesBack)

    # record solutions for 20 time steps
    steps = 19
    history = []
    t = 0.0
    if dim == 1:
        history.append((np.array(phi.value).reshape((nx)), t))
    if dim == 2:
        history.append((np.array(phi.value).reshape((nx, ny)), t))
    if dim == 3:
        history.append((np.array(phi.value).reshape((nx, ny, nz)), t))

    dt = 1 / steps
    for step in range(steps):
        # time.setValue(t)
        eq.solve(var=phi,
                 dt=dt)
        t += dt
        if dim == 1:
            history.append((np.array(phi.value).reshape((nx)), t))
        if dim == 2:
            history.append((np.array(phi.value).reshape((nx, ny)), t))
        if dim == 3:
            history.append(((np.array(phi.value).reshape((nx, ny, nz))), t))

    return history


def generate_plot(n_epocs: int, n_neurons: int,
                  n_points: int, dim: int, mode: str, value_x0,
                  value_x1, value_y0, value_y1,
                  value_z0, value_z1, value_t0) -> tuple[Figure, str]:
    """
    Runs the loop and then generates a plot
    of the loss evolution related to the epochs,
    a voxel plot of the solution obtained by the PINN
    compared with a voxel plot of the fipy solution if dim>1,
    else it generates two contour plots, one with the exact
    solution.In both cases, it also
    returns the l2 loss in respect to
    the expected solution, be it fipy or exact.

    Parameters
    ----------
    n_epochs:int
    The number of epochs for the loop
    n_neurons:int
    The numer of neurons per layer.
    n_points:int
    The number of points for LHS sampling.
    dim:int
    The number of spatil dimensions.
    mode: str
    The type of boundary conditions applied.
    value_x0: float
    The dirichlet condition for x=0
    value_x1: float
    The dirichlet condition for x=1
    value_y0: float
    The dirichlet condition for y=0
    value_y1: float
    The dirichlet condition for y=1
    value_z0: float
    The dirichlet condition for z=0
    value_z1: float
    The dirichlet condition for z=1
    value_t0: float
    The initial condition

    Returns
    -------
    fig:Figure
    Returns the figure for gradio to show.
    l2_loss:str
    Returns a string indicationg the l2_loss.
    """

    # make the parameters float to avoid errors with gradio
    # gradio sliders initialize values with type hint float to 0
    # which is int (same thing with  1)
    value_x0 = float(value_x0)
    value_x1 = float(value_x1)
    value_y0 = float(value_y0)
    value_y1 = float(value_y1)
    value_z0 = float(value_z0)
    value_z1 = float(value_z1)
    value_t0 = float(value_t0)

    # collect the two solutions
    model, loss_list = training_loop(
        n_epocs, n_neurons, n_points, dim, mode, value_x0,
        value_x1, value_y0, value_y1,
        value_z0, value_z1, value_t0)
    history = solve_with_fipy(dim, mode, value_x0,
                              value_x1, value_y0, value_y1,
                              value_z0, value_z1, value_t0)

    # initializing the testing points
    x_test = torch.linspace(0.025, 0.975, 20).view(-1, 1)
    y_test = torch.linspace(0.025, 0.975, 20).view(-1, 1)
    z_test = torch.linspace(0.025, 0.975, 20).view(-1, 1)
    t_test = torch.linspace(0, 1, 20).view(-1, 1)

    # runs different meshgrids and operations for differents dims
    # namely dim=3 needs a different set of points to calculate the loss since
    # the graph is generated at a set time point (and as such refers
    #  to a different space)
    if dim == 1:
        x_test, t_test = torch.meshgrid(
            x_test.squeeze(), t_test.squeeze(), indexing='ij')
        x_test = x_test.reshape(-1, 1)
        t_test = t_test.reshape(-1, 1)

    if dim == 2:
        x_test, y_test, t_test = torch.meshgrid(
            x_test.squeeze(), y_test.squeeze(),
            t_test.squeeze(), indexing='ij')
        x_test = x_test.reshape(-1, 1)
        y_test = y_test.reshape(-1, 1)
        t_test = t_test.reshape(-1, 1)

    if dim == 3:
        x_loss, y_loss, z_loss, t_loss = torch.meshgrid(
            x_test.squeeze(), y_test.squeeze(), z_test.squeeze(),
            t_test.squeeze(), indexing='ij')

        x_test, y_test, z_test = torch.meshgrid(
            x_test.squeeze(), y_test.squeeze(),
            z_test.squeeze(), indexing='ij')

        x_test = x_test.reshape(-1, 1)
        y_test = y_test.reshape(-1, 1)
        z_test = z_test.reshape(-1, 1)
        t_test = t_test.reshape(-1, 1)

        x_loss = x_loss.reshape(-1, 1)
        y_loss = y_loss.reshape(-1, 1)
        z_loss = z_loss.reshape(-1, 1)
        t_loss = t_loss.reshape(-1, 1)

    model.eval()

    # running the model. Again, for dim=3 a special approach since t is set
    # in all cases, two u_pred are generated, a tensor for l2 loss and
    # a numpy array for the graphs
    with torch.no_grad():
        if dim == 1:
            u_pred_tensor = model(x_test, t=t_test)
            u_pred = u_pred_tensor.numpy()
            u_exact_tensor = exact_solution_1D(x_test, t_test)
            u_exact = u_exact_tensor.numpy()

        if dim == 2:
            u_pred_tensor = model(x_test, y_test, t=t_test)
            u_pred = u_pred_tensor.numpy()

        if dim == 3:
            u_pred_tensor = model(x_loss, y_loss, z_loss, t=t_loss)
            u_pred = model(x_test, y_test, z_test,
                           t=torch.full_like(x_test, 0.5)).numpy()

    losses = [item[0] for item in loss_list]
    epochs = [item[1] for item in loss_list]

    if dim == 1:
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(16, 5))

        x_test = x_test.numpy().reshape(20, 20)
        t_test = t_test.numpy().reshape(20, 20)
        u_pred = u_pred.reshape(20, 20)
        u_exact = u_exact.reshape(20, 20)

        fipy_matrices = [item[0] if isinstance(
            item, (tuple, list)) else item for item in history]
        u_fipy = np.stack(fipy_matrices, axis=-1)
        u_exact_tensor = torch.Tensor(u_fipy).reshape(-1, 1)
        u_fipy = u_fipy.reshape(20, 20)

        # contour plots
        c1 = ax1.contourf(x_test, t_test, u_pred, levels=250, cmap='jet')
        ax1.set_title('Prediction (PINN)')
        fig.colorbar(c1, ax=ax1)
        # deprecated exact solutions graph
        # c2 = ax2.contourf(x_test, t_test, u_exact, levels=250, cmap='jet')
        # ax2.set_title('Exact')
        # fig.colorbar(c2, ax=ax2)
        c2 = ax2.contourf(x_test, t_test, u_fipy, levels=250, cmap='jet')
        ax2.set_title('fipy')
        fig.colorbar(c2, ax=ax2)

        # loss plot
        ax3.plot(epochs, losses, label="loss")
        ax3.set_yscale('log')
        ax3.set_xlabel('epoch')
        ax3.set_ylabel('loss')
        ax3.grid(True)

        plt.tight_layout()

    else:
        if dim == 2:
            x_test = x_test.numpy().reshape(20, 20, 20)
            y_test = y_test.numpy().reshape(20, 20, 20)
            t_test = t_test.numpy().reshape(20, 20, 20)
            u_pred = u_pred.reshape(20, 20, 20)

        if dim == 3:
            x_test = x_test.numpy().reshape(20, 20, 20)
            y_test = y_test.numpy().reshape(20, 20, 20)
            z_test = z_test.numpy().reshape(20, 20, 20)
            u_pred = u_pred.reshape(20, 20, 20)

        ds = 1

        if dim == 2:
            x_ds = x_test[::ds, ::ds, ::ds]
            y_ds = y_test[::ds, ::ds, ::ds]
            z_ds = t_test[::ds, ::ds, ::ds]  # NB here z is time!
            u_ds = u_pred[::ds, ::ds, ::ds]

        if dim == 3:
            x_ds = x_test[::ds, ::ds, ::ds]
            y_ds = y_test[::ds, ::ds, ::ds]
            z_ds = z_test[::ds, ::ds, ::ds]
            u_ds = u_pred[::ds, ::ds, ::ds]

        grid_shape = x_ds.shape
        voxels = np.ones(grid_shape, dtype=bool)

        hole = (x_ds > 0.6) & (y_ds < 0.4) & (z_ds > 0.6)
        voxels[hole] = False

        norm_pred = plt.Normalize(u_ds.min(), u_ds.max())
        colors = cm.viridis(norm_pred(u_ds))
        colors[..., 3] = 1.0

        fipy_matrices = [item[0] if isinstance(
            item, (tuple, list)) else item for item in history]
        u_exact = np.stack(fipy_matrices, axis=-1)
        u_exact_tensor = torch.Tensor(u_exact).reshape(-1, 1)
        u_exact_ds = u_exact[::ds, ::ds, ::ds]
        norm_exact = plt.Normalize(u_exact_ds.min(), u_exact_ds.max())

        if dim == 3:
            u_exact = history[9][0]  # fixing t
            u_exact_ds = u_exact[::ds, ::ds, ::ds]

        # set the color scale
        colors_exact = cm.viridis(norm_exact(u_exact_ds))
        colors_exact[..., 3] = 1.0

        fig = plt.figure(figsize=(16, 5))

        # voxel plot of the prediction
        ax1 = fig.add_subplot(1, 3, 1, projection='3d')
        ax1.voxels(voxels, facecolors=colors, edgecolor='k', linewidth=0.2)
        ax1.set_title("Prediction (PINN)")

        # voxel plot of the fipy solution
        ax_exact = fig.add_subplot(1, 3, 2, projection='3d')
        ax_exact.voxels(voxels, facecolors=colors_exact,
                        edgecolor='k', linewidth=0.2)
        ax_exact.set_title("Exact (FiPy)")

        # plot of the loss
        ax2 = fig.add_subplot(1, 3, 3)
        ax2.plot(epochs, losses, label="loss")
        ax2.set_yscale('log')
        ax2.set_xlabel('epoch')
        ax2.set_ylabel('loss')
        ax2.grid(True)

        plt.tight_layout()

    # compute the loss
    l2_loss = nn.functional.mse_loss(u_exact_tensor, u_pred_tensor)

    l2_loss_text = f'L2 loss={l2_loss}'

    return fig, l2_loss_text
