import torch
import torch.nn as nn
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from scipy.stats import qmc
import numpy as np
from fipy import CellVariable, Grid1D, Grid2D
from fipy import Grid3D, TransientTerm, DiffusionTerm
import matplotlib.cm as cm
import math


class PINN(nn.Module):
    """
    A PINN composed of four layers and
    their respective tanh activation function.

    Parameters
    ----------
        n_neurons:int
            Number of neurons
        dim:int
            The number of spatial dimensions (0<dim<4).
        hidden (nn.Sequential)
            The neural network architecture itself, which is
            composed by 4 layers and their tanh activation functions.
    """

    def __init__(self, n_neurons: int = 50, dim: int = 1):
        super(PINN, self).__init__()
        self.hidden = nn.Sequential(
            nn.Linear(dim+1, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, 1)
        )

    def forward(self, *coordinates: torch.Tensor,
                t: torch.Tensor) -> torch.Tensor:
        """
        The core method of the PINN, which approximates u(vec(x),t),
        where vec(x) means the spatial coordinates.

        Parameters
        ----------
            *coordinates:torch.Tensor
                The spatial coordinates (0<dim<4).
            t:torch.Tensor
                The temporal coordinates.

        Returns
        -------
            u: torch.Tensor
                the approximation of u(vec(x),t).
        """

        # concatenate the inputs
        inputs = torch.cat(coordinates + (t,), dim=1)
        pinn = self.hidden(inputs)
        return pinn


def lhs_sample_generator(n_points: int,
                         dim: int) -> tuple[torch.Tensor, ...]:
    """
    A Latin Hypercube Sample (lhs) point generator,
    based on the Quasi-Monte Carlo scipy submodel
    and its method LatinHypercube. Generates a tuple of dim+1
    Tensors of lenght n_points.

    Parameters
    ----------
        n_points:int
            The number of points generated by the function.
        dim:int
            The dimension of the spatial coordinates (0<dim<4).
            For example if the input was 3 you would generate x, y, z, t,
            following classical cartesian nomenclature.

    Returns
    -------
        tuple[torch.Tensor, ...]
            A tuple of Tensors of size dim+1, each Tensor of lenght n_points.
    """
    # create the points
    sampler = qmc.LatinHypercube(d=dim+1, seed=42)
    lhs_samples = sampler.random(n_points)

    # make them usable, first a tensor then an easily unpackable tuple
    lhs_samples = torch.Tensor(lhs_samples)
    lhs_samples.requires_grad = True
    lhs_samples_tuple = tuple(
        (lhs_samples[:, i].view(-1, 1)) for i in range(dim+1))

    return lhs_samples_tuple


def pde_residual(*coordinates: torch.Tensor,
                 t: torch.Tensor, model: nn.Module,
                 D: float = 0.01, R: float = 1) -> torch.Tensor:
    """
    Calculates the residual of the KPP-Fisher equation
    (du_dt-D*(laplacian)-R*u*(1-u)) for a model in input
    in the points given by *coordinates and t.

    Parameters
    ----------
        *coordinates:torch.Tensor
            The spatial coordinates (0<dim<4).
        t:torch.Tensor
            The temporal coordinates.
        D:float=0.01
            The diffusion coefficient.
        R:float=1
            The reaction rate.

    Returns
    -------
        residual:torch.Tensor
            The residual of the KPP-Fisher equation
            (du_dt-D*(laplacian)-R*u*(1-u)) in all the points
            described by *coordinates and t.
    """

    u = model(*coordinates, t=t)

    # temporal derivative
    du_dt = torch.autograd.grad(u, t, torch.ones_like(
        u), create_graph=True)[0]

    # compute the laplacian
    laplacian = 0
    for coord in coordinates:
        # first derivative
        du_dcoord = torch.autograd.grad(
            u, coord, create_graph=True, grad_outputs=torch.ones_like(u))[0]
        # second derivative
        d2u_dcoord2 = torch.autograd.grad(
            du_dcoord, coord, create_graph=True,
            grad_outputs=torch.ones_like(du_dcoord))[0]

        laplacian += d2u_dcoord2

    # kpp-fisher residual
    residual = du_dt-D*(laplacian)-R*u*(1-u)
    return residual


def pde_residual_benchmark(r: torch.Tensor,
                           t: torch.Tensor, model: nn.Module,  d: int,
                           D: float = 0.01, R: float = 1) -> torch.Tensor:
    """
    Calculates the residual of the KPP-Fisher equation, simplified for
    radially symmetrical conditions, namely
    du_dt-D*(d2u_dr2+((d-1)/r)*du_dr)-R*u*(1-u),
    where d=2 for the 2d and 3 for 3d, for the input model.

    Parameters
    ----------
        r:torch.Tensor
            The radial coordinates.
        t:torch.Tensor
            The temporal coordinates.
        model: nn.Module
            The model which will be evaluated
        D:float=0.01
            The diffusion coefficient.
        d: int
            The d coefficient for the equation. d=2 for the 2d and 3 for 3d.
        R:float=1
            The reaction rate.

    Returns
    -------
        residual:torch.Tensor
            The residual of the simplified KPP-Fisher equation for the input
            model.
    """

    u = model(r, t=t)

    # temporal derivative
    du_dt = torch.autograd.grad(u, t, torch.ones_like(
        u), create_graph=True)[0]

    # first derivative
    du_dr = torch.autograd.grad(
        u, r, create_graph=True, grad_outputs=torch.ones_like(u))[0]
    # second derivative
    d2u_dr2 = torch.autograd.grad(
        du_dr, r, create_graph=True,
        grad_outputs=torch.ones_like(du_dr))[0]

    # kpp-fisher residual
    residual = du_dt-D*(d2u_dr2+(d-1)*torch.pow(r, -1)*du_dr)-R*u*(1-u)
    return residual


def loss_function_sphere_benchmark(r: torch.Tensor,
                                   t: torch.Tensor,
                                   model: nn.Module, d: int,
                                   value_t0: float = 0.0) -> torch.Tensor:
    """
    Calculates the loss for a model in the case of a radially symmetrical
    initial condition, as the sum of the squared values of the mean of
    u-value_t0 at t=0, du/dt at r=0, 1 and the squared pde.

    Parameters
    ----------
        r:torch.Tensor
            The radial coordinates.
        t:torch.Tensor
            The temporal coordinates.
        model: nn.Module
            The PINN.
        D:float=0.01
            The diffusion coefficient.
        value_t0: float
            The initial condition.

    Returns
    -------
        loss: torch.Tensor
            The total loss, as the sum of the one for the boundaries,
            the initial condition and the pde.
    """
    # initial condition loss
    u_pr = model(r, t=torch.zeros_like(t))
    u_ex = torch.full_like(t, value_t0)
    loss_ic = torch.mean((u_pr-u_ex)**2)

    # boundary conditions loss (neumann & regularity)
    r_0 = torch.zeros_like(r, requires_grad=True)
    r_1 = torch.ones_like(r, requires_grad=True)
    u_pr_0 = model(r_0, t=t)
    u_pr_1 = model(r_1, t=t)
    du_dr_0 = torch.autograd.grad(
        u_pr_0, r_0, create_graph=True,
        grad_outputs=torch.ones_like(u_pr))[0]
    du_dr_1 = torch.autograd.grad(
        u_pr_1, r_1, create_graph=True,
        grad_outputs=torch.ones_like(u_pr))[0]
    loss_bc = torch.mean(du_dr_0**2)+torch.mean(du_dr_1**2)

    # residual loss
    loss_pde = torch.mean(pde_residual_benchmark(r, t=t, model=model, d=d)**2)

    # total loss
    loss = loss_bc+loss_ic+loss_pde

    return loss


def neumann_condition(*coordinates: torch.Tensor,
                      t: torch.Tensor, model: nn.Module) -> torch.Tensor:
    """
    Computes the Neumann condition loss (null flux) for a
    square, rectangular or 1d [0, 1]^dim domain.

    Parameters
    ----------
        *coordinates: torch.Tensor
            The spatial coordinates.
        t: torch.Tensor
            The temporal coordinates.
        model: nn.Module
            The model for evaluation.

    Returns
    -------
        loss: torch.Tensor
            The Neumann condition loss, equal to the square mean of
            the first derivative in the input points.
    """
    loss = 0.0
    # compute the first derivative and sum it to the loss
    for i, coord in enumerate(coordinates):
        for boundary_val in (0.0, 1.0):
            boundary_coords = list(coordinates)
            boundary_coords[i] = torch.full_like(coord, boundary_val,
                                                 requires_grad=True)

            u_b = model(*boundary_coords, t=t)
            du_dcoord = torch.autograd.grad(
                u_b, boundary_coords[i], create_graph=True,
                grad_outputs=torch.ones_like(u_b))[0]
            loss += torch.mean(du_dcoord**2)
    return loss


def dirichlet_condition(*coordinates: torch.Tensor,
                        t: torch.Tensor, model: nn.Module,
                        value_x0: float = 0.0,
                        value_x1: float = 0.0,
                        value_y0: float = 0.0, value_y1: float = 0.0,
                        value_z0: float = 0.0,
                        value_z1: float = 0.0) -> torch.Tensor:
    """
    Computes the dirichlet conditions' loss for a
    square, rectangular or 1d [0, 1]^dim domain.

    Parameters
    ----------
        *coordinates: torch.Tensor
            The spatial coordinates.
        t: torch.Tensor
            The temporal coordinates.
        model: nn.Module
            The PINN.
        value_x0: float
            The dirichlet condition for x=0
        value_x1: float
            The dirichlet condition for x=1
        value_y0: float
            The dirichlet condition for y=0
        value_y1: float
            The dirichlet condition for y=1
        value_z0: float
            The dirichlet condition for z=0
        value_z1: float
            The dirichlet condition for z=1

    Returns
    -------
        loss: torch.Tensor
            The Dirichlet condition loss, which is the squared difference
            between the expected value (the set boundary value) and the value
            computed by the model.
    """
    loss = 0.0

    # create a matrix for the boundary conditions so that
    # u_ex_matrix[i][0]=value_i0 etc
    u_ex_matrix = [[value_x0, value_x1],
                   [value_y0, value_y1],
                   [value_z0, value_z1]]

    # compute the loss
    for i, coord in enumerate(coordinates):
        for boundary_index, boundary_val in enumerate((0.0, 1.0)):
            boundary_coords = list(coordinates)
            boundary_coords[i] = torch.full_like(coord, boundary_val,
                                                 requires_grad=True)

            u_pr = model(*boundary_coords, t=t)
            u_ex = u_ex_matrix[i][boundary_index]
            loss += torch.mean((u_pr-u_ex)**2)
    return loss


def loss_function(*coordinates: torch.Tensor, mode: str = "dirichlet",
                  t: torch.Tensor,
                  model: nn.Module, value_x0: float = 0.0,
                  value_x1: float = 0.0,
                  value_y0: float = 0.0, value_y1: float = 0.0,
                  value_z0: float = 0.0,
                  value_z1: float = 0.0,
                  value_t0: float = 0.0) -> torch.Tensor:
    """
    Computes the loss function as the sum of the initial conditions loss,
    boundary conditions loss and the residual loss for a
    square, rectangular or 1d [0, 1]^dim domain.

    Parameters
    ----------
        *coordinates:torch.Tensor
            The spatial coordinates (0<dim<4).
        mode: str = "dirichlet"
            The type of boundary conditions applied.
        t:torch.Tensor
            The temporal coordinates
        model:nn.Module
            The model to train.
        value_x0: float
            The dirichlet condition for x=0
        value_x1: float
            The dirichlet condition for x=1
        value_y0: float
            The dirichlet condition for y=0
        value_y1: float
            The dirichlet condition for y=1
        value_z0: float
            The dirichlet condition for z=0
        value_z1: float
            The dirichlet condition for z=1
        value_t0: float
            The initial condition.

    Returns
    -------
        loss: torch.Tensor
            The loss function numerical result, which is calculated by
            using pde_residual to calculate the physics loss, mode_condition
            for the boundary condition and by calculating the initial condition
            loss inside the function, as the squared difference between the
            result obtained by the model and value_t0.
    """

    # initial condition loss
    u_pr = model(*coordinates, t=torch.zeros_like(t))
    if mode == 'exact':
        u_ex = exact_solution_1D(
            coordinates[0], torch.zeros_like(coordinates[0]))
    else:
        u_ex = torch.full_like(t, value_t0)
    loss_ic = torch.mean((u_pr-u_ex)**2)

    # boundary conditions loss
    if mode == 'neumann':
        loss_bc = neumann_condition(*coordinates, t=t, model=model)
    elif mode == 'exact':
        u_0_pr = model(torch.zeros_like(t), t=t)
        u_1_pr = model(torch.full_like(t, 1), t=t)
        u_0_ex = exact_solution_1D(torch.zeros_like(t), t=t)
        u_1_ex = exact_solution_1D(torch.full_like(t, 1), t=t)

        loss_bc = torch.mean((u_0_pr - u_0_ex)**2) + \
            torch.mean((u_1_ex-u_1_pr)**2)
    elif mode == 'dirichlet':
        # to avoid disagreements in the angles
        t_bc = 0.05 + (1 - 0.05) * t
        loss_bc = dirichlet_condition(*coordinates, t=t_bc,
                                      model=model, value_x0=value_x0,
                                      value_x1=value_x1,
                                      value_y0=value_y0,
                                      value_y1=value_y1,
                                      value_z0=value_z0,
                                      value_z1=value_z1)
    else:
        raise (NameError('Invalid mode'))

    # residual loss
    loss_pde = torch.mean(pde_residual(*coordinates, t=t, model=model)**2)

    # total loss
    loss = loss_bc+loss_ic+loss_pde

    return loss


def lhs_sample_generator_sphere_boundary(
    n_points: int, dim: int,
) -> tuple[torch.Tensor, torch.Tensor] | tuple[
        torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Generates a number of points on the unit sphere/circle boundary using lhs.

    Parameters
    ----------
        n_points:int
            The numer of points to be generated.
        dim:int
            The number of spatial dimensions (either 2 or 3).

    Returns
    -------
        tuple[torch.Tensor, ...]
            the spatial coordinates of the generated points,
            made by dim Tensors of lenght n_points.
    """

    lhs_samples_tuple = lhs_sample_generator(
        n_points, dim-1)

    # then they are transformed into polar/spherical coords
    if dim == 3:
        longitude = lhs_samples_tuple[0]*2*math.pi
        # not by rescaling for spatial uniformity
        colatitude = torch.acos(1 - 2*lhs_samples_tuple[1])

        x = torch.sin(colatitude)*torch.cos(longitude)
        y = torch.sin(colatitude)*torch.sin(longitude)
        z = torch.cos(colatitude)
        return x, y, z

    if dim == 2:
        theta = lhs_samples_tuple[0]*2*math.pi

        x = torch.cos(theta)
        y = torch.sin(theta)
        return x, y


def lhs_sample_generator_sphere_inside(
    n_points: int, dim: int,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor] | tuple[
        torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Generates a number of points inside the unit circle/sphere using lhs.

    Parameters
    ----------
        n_points:int
            The numer of points to be generated.
        dim:int
            the number of spatial dimensions (either 2 or 3).

    Returns
    -------
        tuple[torch.Tensor, ...]
            The coordinates of the generated points, made by
            dim+1 tensors of lenght n_points
    """

    lhs_samples_tuple = lhs_sample_generator(
        n_points, dim)  # points generated with lhs

    t = lhs_samples_tuple[dim]

    # then they are transformed them into polar/spherical coords
    if dim == 3:
        # reshaped for volume uniformity
        radius = torch.pow(lhs_samples_tuple[2], 1/3)
        longitude = lhs_samples_tuple[0]*2*math.pi
        # not by rescaling for spatial uniformity
        colatitude = torch.acos(1 - 2*lhs_samples_tuple[1])

        x = (radius*torch.sin(colatitude)*torch.cos(longitude)
             ).detach().requires_grad_(True)
        y = (radius*torch.sin(colatitude)*torch.sin(longitude)
             ).detach().requires_grad_(True)
        z = (radius*torch.cos(colatitude)).detach().requires_grad_(True)

        return x, y, z, t
    if dim == 2:
        # resh for area uniformity
        theta = lhs_samples_tuple[0]*2*math.pi
        radius = torch.sqrt(lhs_samples_tuple[1])

        x = (radius*torch.cos(theta)).detach().requires_grad_(True)
        y = (radius*torch.sin(theta)).detach().requires_grad_(True)
        return x, y, t


def neumann_condition_sphere(*coordinates: torch.Tensor,
                             t: torch.Tensor,
                             model: nn.Module) -> torch.Tensor:
    """
    Calculates the loss for Neumann conditions in the unit circle/sphere
    for the input model.

    Parameters
    ----------
        *coordinates: torch.Tensor
            The spatial coordinates.
        t: torch.Tensor
            The temporal coordinates.
        model: nn.Module
            The model to be trained.

    Returns
    -------
        loss: torch.Tensor
        The loss determined by Neumann conditions as the mean squared
        first derivatives.
    """
    loss = 0.0
    u_b = model(*coordinates, t=t)
    output_type = torch.ones_like(u_b)  # necessary for flake8 linetoolong

    # compute the first derivative and sum it to the loss
    neumann = sum(torch.autograd.grad(u_b, coord, create_graph=True,
                                      grad_outputs=output_type)[0]*coord
                  for coord in coordinates)
    loss += torch.mean(neumann**2)
    return loss


def loss_function_sphere(*coordinates: torch.Tensor, t: torch.Tensor,
                         n_points: int, dim: int,
                         value_t0: float, model: nn.Module) -> torch.Tensor:
    """
    Calculates the total loss for a sphere/circle, by summing the boundary loss
    the physics loss and the initial conditions loss.

    Parameters
    ----------
        *coordinates: torch.Tensor
            The spatial coordinates.
        t: torch.Tensor
            The temporal coordinates.
        n_points: int
            The number of points (used for the boundary)
        dim: int
            The number of spatial dimensions (either 2 or 3)
        value_t0: float
            The initial condition.
        model: nn.Module
            The mode to be trained.

    Returns
    -------
        total_loss: torch.Tensor
            The total loss, the sum of the boundary conditions loss calculated
            with neuman_condition_sphere, the initial condition loss and the
            physics loss calculated as the mean squared pde_residual.
    """
    # boundary loss
    boundary_coords = lhs_sample_generator_sphere_boundary(n_points, dim)
    loss_bc = neumann_condition_sphere(*boundary_coords, t=t, model=model)

    # physics loss, only inside the sphere
    loss_pde = torch.mean(pde_residual(*coordinates, t=t, model=model)**2)

    # initial condition loss
    u_pr = model(*coordinates, t=torch.zeros_like(t))
    u_ex = torch.full_like(t, value_t0)
    loss_ic = torch.mean((u_pr-u_ex)**2)

    total_loss = loss_bc+loss_pde+loss_ic
    return total_loss


def exact_solution_1D(x: torch.Tensor,
                      t: torch.Tensor,
                      D: float = 0.01,
                      R: float = 1) -> torch.Tensor:
    """
    Calculates the exact solution of the KPP-Fisher equation in 1D with
    specific conditions.

    Parameters
    ----------
        x:torch.Tensor
            The spatial coordinates.
        t:torch.Tensor
            The temporal coordinates.
        D:float=0.01
            The diffusion coefficient.
        R:float=1
            The reaction rate.

    Returns
    -------
        exact_solution:torch.Tensor
            The exact solution of the KPP-Fisher equation in 1D,
            namely (1+e^(((R/(6*D))**0.5)*x-5*R*t/6))^-2.
    """

    exponent = ((R/(6*D))**0.5)*x-5*R*t/6
    exp = torch.exp(exponent)
    exact_solution = (1+exp)**(-2)
    return exact_solution


def training_loop(n_epochs: int, n_neurons: int,
                  n_points: int, dim: int, mode: str,
                  value_x0: float, value_x1: float,
                  value_y0: float, value_y1: float, value_z0: float,
                  value_z1: float,
                  value_t0: float) -> tuple[nn.Module, list]:
    """
    Runs n_epochs loops to train a PINN by evaluating the loss
    using loss_function or loss_function_sphere if mode=='sphere'.

    Parameters
    ----------
        n_epochs:int
            The number of epochs for the training loop.
        n_neurons:int
            The numer of neurons per layer.
        n_points:int
            The number of points for LHS.
        dim:int
            The number of spatial dimensions.
        mode: str
            The type of boundary conditions.
        value_x0: float
            The dirichlet condition for x=0
        value_x1: float
            The dirichlet condition for x=1
        value_y0: float
            The dirichlet condition for y=0
        value_y1: float
            The dirichlet condition for y=1
        value_z0: float
            The dirichlet condition for z=0
        value_z1: float
            The dirichlet condition for z=1
        value_t0: float
            The initial condition.

    Returns
    -------
        model:nn.Module
            The trained PINN.
        loss_list:list
            A list containing the loss every 10 epochs.
    """

    model = PINN(n_neurons, dim)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # reinitialize the model parameters
    model.apply(lambda m: m.reset_parameters()
                if hasattr(m, 'reset_parameters') else None)

    # sample point generation
    if mode != 'sphere':
        all_samples = list(lhs_sample_generator(n_points, dim))
    else:
        all_samples = list(lhs_sample_generator_sphere_inside(n_points, dim))

    spatial_coords = tuple(all_samples[:-1])
    t = all_samples[-1]

    loss_list = []

    for epoch in range(n_epochs):
        model.train()
        if mode != 'sphere':
            loss = loss_function(*spatial_coords, t=t, model=model, mode=mode,
                                 value_x0=value_x0, value_x1=value_x1,
                                 value_y0=value_y0, value_y1=value_y1,
                                 value_z0=value_z0, value_z1=value_z1,
                                 value_t0=value_t0)
        else:
            loss = loss_function_sphere(
                *spatial_coords, n_points=n_points,
                t=t, dim=dim, model=model, value_t0=value_t0)

        # collect loss for loss evolution
        if epoch % 10 == 0:
            loss_list.append([loss.item(), epoch])

        # backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    return model, loss_list


def training_loop_benchmarking(n_epochs: int, n_neurons: int,
                               n_points: int, dim: int,
                               value_t0: float) -> tuple[nn.Module, list]:
    """
    Runs n_epochs loops to train a PINN for the radially symmetrical case.

    Parameters
    ----------
        n_epochs:int
            The number of epochs for the training loop.
        n_neurons:int
            The numer of neurons per layer.
        n_points:int
            The number of points for LHS sampling.
        dim:int
            The number of spatial dimensions.
        value_t0: float
            The initial condition

    Returns
    -------
        model:nn.Module
            The trained PINN.
    """
    model = PINN(n_neurons, 1)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # reinitialize the model parameters
    model.apply(lambda m: m.reset_parameters()
                if hasattr(m, 'reset_parameters') else None)

    # sample point generation
    r, t = lhs_sample_generator(n_points, 1)

    for epoch in range(n_epochs):
        model.train()
        loss = loss_function_sphere_benchmark(
            r, t=t, model=model, value_t0=value_t0, d=dim)

        # backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    return model


def solve_with_fipy(dim: int, mode: str, value_x0: float, value_x1: float,
                    value_y0: float, value_y1: float, value_z0: float,
                    value_z1: float,
                    value_t0: float) -> list:
    """
    Solves the equation with fipy with
    dirichlet or neumann boundary conditions for a
    square, rectangular or 1d [0, 1]^dim domain.

    Parameters
    ----------
        dim:int
            The number of spatial dimensions taken into consideration (0<dim<4)
        mode: str
            The type of boundary conditions applied.
        value_x0: float
            The dirichlet condition for x=0
        value_x1: float
            The dirichlet condition for x=1
        value_y0: float
            The dirichlet condition for y=0
        value_y1: float
            The dirichlet condition for y=1
        value_z0: float
            The dirichlet condition for z=0
        value_z1: float
            The dirichlet condition for z=1
        value_t0: float
            The initial condition.

    Returns
    -------
        history:list
            A list containing u(vec(x), t) for 20^(dim+1) data points.
    """

    nx = 20
    ny = nx
    nz = nx
    dx = 0.05
    dy = dx
    dz = dx

    if dim == 1:
        mesh = Grid1D(dx=dx, nx=nx)
    if dim == 2:
        mesh = Grid2D(dx=dx, dy=dy, nx=nx, ny=ny)
    if dim == 3:
        mesh = Grid3D(dx=dx, dy=dy, dz=dz, nx=nx, ny=ny, nz=nz)

    phi = CellVariable(name='solution variable', mesh=mesh, value=value_t0)

    # define kpp-fisher
    eq = TransientTerm() == DiffusionTerm(coeff=0.01) + phi*(1-phi)

    # set boundary conditions
    if mode == 'dirichlet':
        if dim >= 1:
            phi.constrain(value_x0, where=mesh.facesLeft)
            phi.constrain(value_x1, where=mesh.facesRight)

        if dim >= 2:  # add conditions for dim==2
            phi.constrain(value_y0, where=mesh.facesBottom)
            phi.constrain(value_y1, where=mesh.facesTop)

        if dim >= 3:  # add conditions for dim=3
            phi.constrain(value_z0, where=mesh.facesFront)
            phi.constrain(value_z1, where=mesh.facesBack)

    elif mode == 'neumann':
        if dim >= 1:
            phi.faceGrad.constrain(0.0, where=mesh.facesLeft)
            phi.faceGrad.constrain(0.0, where=mesh.facesRight)

        if dim >= 2:
            phi.faceGrad.constrain(0.0, where=mesh.facesBottom)
            phi.faceGrad.constrain(0.0, where=mesh.facesTop)

        if dim >= 3:
            phi.faceGrad.constrain(0.0, where=mesh.facesFront)
            phi.faceGrad.constrain(0.0, where=mesh.facesBack)

    # record solutions for 20 time steps
    steps = 19
    history = []
    t = 0.0
    # first step
    if dim == 1:
        history.append((np.array(phi.value).reshape((nx)), t))
    if dim == 2:
        history.append((np.array(phi.value).reshape((nx, ny)), t))
    if dim == 3:
        history.append((np.array(phi.value).reshape((nx, ny, nz)), t))

    dt = 1 / steps
    for step in range(steps):
        # time.setValue(t)
        eq.solve(var=phi,
                 dt=dt)
        t += dt
        if dim == 1:
            history.append((np.array(phi.value).reshape((nx)), t))
        if dim == 2:
            history.append((np.array(phi.value).reshape((nx, ny)), t))
        if dim == 3:
            history.append((np.array(phi.value).reshape((nx, ny, nz)), t))

    return history


def l2_loss_sphere(n_points: int, model: nn.Module,
                   benchmarking_model: nn.Module, dim: int) -> str:
    """
    Calculates the l2 loss between the PINN trained on cartesian coordinates
    and the one on the symmatrical equation for a circular/spherical domain.

    Parameters
    ----------
        n_point: int
            The number of sampling points.
        model: nn.Module
            The PINN trained on cartesian coordinates.
        benchmarking_model: nn.Module
            The Pinn trained on the simple one dimensional equation.
        dim: int
            The number of spatial dimensions.

    Returns
    -------
        l2_loss_text: str
        A string containing the l2 loss and the maximum
        difference between the models.
    """
    # sample some points then calculate their radius
    *coords, t = list(lhs_sample_generator_sphere_inside(n_points, dim))
    radius = torch.sqrt(sum(c**2 for c in coords)).detach()

    # compute the trained models' outputs
    with torch.no_grad():
        u_cartesian = model(*coords, t=t)
        u_radial = benchmarking_model(radius, t=t)

    # calculate the maximum difference
    diff = u_cartesian - u_radial
    max_diff = torch.max(torch.abs(diff))

    # calculate l2 loss
    l2_loss = nn.functional.mse_loss(u_cartesian, u_radial)

    l2_loss_text = f'L2 loss = {l2_loss}, maximum difference = {max_diff}'

    return l2_loss_text


def generate_plot(n_epochs: int, n_neurons: int,
                  n_points: int, dim: int, mode: str, value_x0,
                  value_x1, value_y0, value_y1,
                  value_z0, value_z1, value_t0) -> tuple[Figure, str]:
    """
    Trains a PINN and then generates a plot
    of the loss evolution related to the epochs,
    a voxel plot of the solution obtained by the PINN
    compared with a voxel plot of the fipy solution if dim>1 and mode!=sphere,
    if mode=exact it generates two contour plots, one with the exact
    solution.In both cases, it also
    returns the l2 loss in respect to
    the expected solution, be it fipy or exact.
    For the sphere, the comparison is shown in different times
    with another PINN, trained on the simpified equation for radial
    simmetry, and the l2 loss is comput in respect to that, too.
    It is also calculated
    the maximum difference between those two.

    Parameters
    ----------
        n_epochs:int
            The number of epochs for the loop
        n_neurons:int
            The numer of neurons per layer.
        n_points:int
            The number of points for LHS sampling.
        dim:int
            The number of spatial dimensions.
        mode: str
            The type of boundary conditions applied.
        value_x0: float
            The dirichlet condition for x=0
        value_x1: float
            The dirichlet condition for x=1
        value_y0: float
            The dirichlet condition for y=0
        value_y1: float
            The dirichlet condition for y=1
        value_z0: float
            The dirichlet condition for z=0
        value_z1: float
            The dirichlet condition for z=1
        value_t0: float
            The initial condition.

    Returns
    -------
        fig:Figure
            A figure with the aformentioned plots depending on the mode.
        l2_loss:str
            Returns a string indicationg the l2_loss
            (and maximum difference if mode=sphere).
    """

    # make the parameters float to avoid errors with gradio
    # gradio sliders initialize values with type hint float to 0
    # which is int (same thing with  1)
    value_x0 = float(value_x0)
    value_x1 = float(value_x1)
    value_y0 = float(value_y0)
    value_y1 = float(value_y1)
    value_z0 = float(value_z0)
    value_z1 = float(value_z1)
    value_t0 = float(value_t0)

    if mode == 'sphere' and dim == 1:
        raise NameError('Mode sphere only works with dim!=1')
    if mode == 'exact' and dim != 1:
        raise NameError('Mode sphere only works with dim==1')

    # collect the two solutions
    model, loss_list = training_loop(
        n_epochs, n_neurons, n_points, dim, mode, value_x0,
        value_x1, value_y0, value_y1,
        value_z0, value_z1, value_t0)
    if mode == 'sphere':
        benchmarking_model = training_loop_benchmarking(
            n_epochs, n_neurons, n_points, dim, value_t0)
    else:
        history = solve_with_fipy(dim, mode, value_x0,
                                  value_x1, value_y0, value_y1,
                                  value_z0, value_z1, value_t0)

    low, high = (-1.0, 1.0) if mode == 'sphere' else (0.025, 0.975)
    # initializing the testing points
    spatial_axis = torch.linspace(low, high, 20)
    t_test = torch.linspace(0, 1, 20)
    if mode == "sphere":
        r_bench = torch.linspace(0, 1, 20).view(-1, 1)

    if dim == 1 or dim == 2:
        axes = [spatial_axis] * dim + [t_test]
        grids = torch.meshgrid(*axes, indexing='ij')
        flat_grids = [g.reshape(-1, 1) for g in grids]

        if dim == 1:
            x_test, t_test = flat_grids
        elif dim == 2:
            x_test, y_test, t_test = flat_grids

    elif dim == 3:
        test_axes = [spatial_axis]*dim
        test_grids = torch.meshgrid(*test_axes, indexing='ij')
        flat_test_grids = [g.reshape(-1, 1) for g in test_grids]

        x_test, y_test, z_test = flat_test_grids

        loss_axes = [spatial_axis]*dim+[t_test]
        loss_grids = torch.meshgrid(*loss_axes, indexing='ij')
        flat_loss_grids = [g.reshape(-1, 1) for g in loss_grids]

        x_loss, y_loss, z_loss, t_loss = flat_loss_grids

    model.eval()

    # running the model. Again, for dim=3 a special approach since t is set
    # in all cases, two u_pred are generated, a tensor for l2 loss and
    # a numpy array for the graphs
    with torch.no_grad():
        if dim == 1:
            u_pred_tensor = model(x_test, t=t_test)
            u_pred = u_pred_tensor.numpy()
            if mode == 'exact':
                u_exact_tensor = exact_solution_1D(x_test, t_test)
                u_exact = u_exact_tensor.numpy()

        if dim == 2:
            u_pred_tensor = model(x_test, y_test, t=t_test)
            u_pred = u_pred_tensor.numpy()

        if dim == 3:
            u_pred_tensor = model(x_loss, y_loss, z_loss, t=t_loss)
            u_pred = model(x_test, y_test, z_test,
                           t=torch.full_like(x_test, 0.5)).numpy()

    losses = [item[0] for item in loss_list]
    epochs = [item[1] for item in loss_list]

    if dim == 1:
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(16, 5))

        x_test = x_test.numpy().reshape(20, 20)
        t_test = t_test.numpy().reshape(20, 20)
        u_pred = u_pred.reshape(20, 20)
        if mode == 'exact':
            u_exact = u_exact.reshape(20, 20)

        fipy_matrices = [item[0] if isinstance(
            item, (tuple, list)) else item for item in history]
        u_fipy = np.stack(fipy_matrices, axis=-1)
        if mode != 'exact':
            u_exact_tensor = torch.Tensor(u_fipy).reshape(-1, 1)
            u_fipy = u_fipy.reshape(20, 20)

        # contour plots
        c1 = ax1.contourf(x_test, t_test, u_pred, levels=250, cmap='jet')
        ax1.set_title('Prediction (PINN)')
        fig.colorbar(c1, ax=ax1)
        if mode != "exact":
            c2 = ax2.contourf(x_test, t_test, u_fipy, levels=250, cmap='jet')
        else:
            c2 = ax2.contourf(x_test, t_test, u_exact, levels=250, cmap='jet')
        ax2.set_title('fipy')
        fig.colorbar(c2, ax=ax2)

        # loss plot
        ax3.plot(epochs, losses, label="loss")
        ax3.set_yscale('log')
        ax3.set_xlabel('epoch')
        ax3.set_ylabel('loss')
        ax3.grid(True)

        plt.tight_layout()

        l2_loss = nn.functional.mse_loss(u_exact_tensor, u_pred_tensor)
        l2_loss_text = f'L2 loss={l2_loss}'

    else:
        if dim == 2:
            x_test = x_test.numpy().reshape(20, 20, 20)
            y_test = y_test.numpy().reshape(20, 20, 20)
            t_test = t_test.numpy().reshape(20, 20, 20)
            u_pred = u_pred.reshape(20, 20, 20)

        elif dim == 3:
            x_test = x_test.numpy().reshape(20, 20, 20)
            y_test = y_test.numpy().reshape(20, 20, 20)
            z_test = z_test.numpy().reshape(20, 20, 20)
            u_pred = u_pred.reshape(20, 20, 20)

        ds = 1
        x_ds = x_test[::ds, ::ds, ::ds]
        y_ds = y_test[::ds, ::ds, ::ds]
        z_ds = z_test[::ds, ::ds,
                      # freeze time for 3d
                      ::ds] if dim == 3 else t_test[::ds, ::ds, ::ds]
        u_ds = u_pred[::ds, ::ds, ::ds]

        # create the points for the voxel plot
        # to rescale the axes
        n = 20

        x_edges = np.linspace(x_ds.min(), x_ds.max(), n + 1)
        y_edges = np.linspace(y_ds.min(), y_ds.max(), n + 1)
        z_edges = np.linspace(z_ds.min(), z_ds.max(), n + 1) if dim == 3 else \
            np.linspace(t_test.min(), t_test.max(), n + 1)

        X, Y, Z = np.meshgrid(x_edges, y_edges, z_edges, indexing='ij')

        grid_shape = x_ds.shape

        # if we have a sphere we want to only see it
        # so the condition for voxels is different
        if mode != 'sphere':
            voxels = np.ones(grid_shape, dtype=bool)
            hole = (x_ds > 0.6) & (y_ds < 0.4) & (z_ds > 0.6)
            voxels[hole] = False
        else:
            if mode == 'sphere':
                r_squared_ds = x_ds**2 + y_ds**2 + \
                    (z_ds**2 if dim == 3 else 0.0)
                voxels = r_squared_ds <= 1.0

        norm_pred = plt.Normalize(u_ds.min(), u_ds.max())
        colors = cm.viridis(norm_pred(u_ds))
        colors[..., 3] = 1.0

        if mode != 'sphere':
            fipy_matrices = [item[0] if isinstance(
                item, (tuple, list)) else item for item in history]
            u_exact = np.stack(fipy_matrices, axis=-1)
            u_exact_tensor = torch.Tensor(u_exact).reshape(-1, 1)
            u_exact_ds = u_exact[::ds, ::ds, ::ds]
            norm_exact = plt.Normalize(u_exact_ds.min(), u_exact_ds.max())

            if dim == 3:
                u_exact = history[9][0]  # fixing t
                u_exact_ds = u_exact[::ds, ::ds, ::ds]

            # set the color scale
            colors_exact = cm.viridis(norm_exact(u_exact_ds))
            colors_exact[..., 3] = 1.0

        fig = plt.figure(figsize=(16, 5))

        # voxel plot of the prediction
        ax1 = fig.add_subplot(1, 3, 1, projection='3d')

        ax1.voxels(X, Y, Z, voxels, facecolors=colors,
                   edgecolor='k', linewidth=0.2)
        ax1.set_title("Prediction (PINN)")

        if mode != 'sphere':
            # voxel plot of the fipy solution
            ax_exact = fig.add_subplot(1, 3, 2, projection='3d')
            ax_exact.voxels(X, Y, Z, voxels, facecolors=colors_exact,
                            edgecolor='k', linewidth=0.2)
            ax_exact.set_title("Exact (FiPy)")
        else:
            # plot comparing u(r,t)
            ax_r = fig.add_subplot(1, 3, 2)

            t_values = (0.0, 0.25, 0.5, 0.75, 1.0)
            colors = cm.viridis(np.linspace(0, 1, len(t_values)))

            for t_val, color in zip(t_values, colors):
                with torch.no_grad():
                    t_fixed = torch.full_like(r_bench, t_val)
                    u_radial = benchmarking_model(
                        r_bench, t=t_fixed).numpy().flatten()
                    if dim == 2:
                        # (x, 0) for simplicity
                        u_cart_ray = model(r_bench, torch.zeros_like(
                            r_bench), t=t_fixed).numpy().flatten()
                    else:
                        # (x, 0, 0) for simplicity
                        u_cart_ray = model(r_bench, torch.zeros_like(r_bench),
                                           torch.zeros_like(r_bench),
                                           t=t_fixed).numpy().flatten()

                ax_r.plot(r_bench.numpy().flatten(), u_cart_ray,
                          color=color, label=f'Cartesian t={t_val}')
                ax_r.plot(r_bench.numpy().flatten(),
                          u_radial, '--', color=color,
                          label=f'Radial t={t_val}')

            ax_r.set_xlabel('r')
            ax_r.set_ylabel('u(r, t)')
            ax_r.legend()
            ax_r.grid(True)

        # plot of the loss
        ax2 = fig.add_subplot(1, 3, 3)
        ax2.plot(epochs, losses, label="loss")
        ax2.set_yscale('log')
        ax2.set_xlabel('epoch')
        ax2.set_ylabel('loss')
        ax2.grid(True)

        plt.tight_layout()
        if mode != 'sphere':
            # compute the loss
            l2_loss = nn.functional.mse_loss(u_exact_tensor, u_pred_tensor)

            l2_loss_text = f'L2 loss={l2_loss}'
        else:
            l2_loss_text = l2_loss_sphere(
                n_points, model, benchmarking_model, dim)

    return fig, l2_loss_text
