import torch
import torch.nn as nn
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from scipy.stats import qmc


class PINN_1d(nn.Module):
    """
    The PINN architecture in 1D.

    Parameters
    ----------
    n_neurons:int
    Number of neurons
    hidden (nn.Sequential)
    the neural network architecture itself, which is
    composed by its 4 layers and their Tanh activation functions.
    """

    def __init__(self, n_neurons: int = 50):
        super(PINN_1d, self).__init__()
        self.hidden = nn.Sequential(  # 4 layers neural network
            nn.Linear(2, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, n_neurons),
            nn.Tanh(),
            nn.Linear(n_neurons, 1)
        )

    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        """
        The core method of the PINN, which approximates u(x,t).

        Parameters
        ----------
        x:torch.Tensor
            The spatial coordinates
        t:torch.Tensor
            The temporal coordinates

        Returns
        -------
        u: torch.Tensor
            the approximation of u(x,t)
        """

        inputs = torch.cat([x, t], dim=1)  # concatenate the inputs
        return self.hidden(inputs)


def lhs_sample_generator(n_points: int,
                         dim: int) -> tuple[torch.Tensor, ...]:
    """
    The latin hypercube sample point generator.

    Parameters
    ----------
    n_point:int
        The number of point generated by the function
    dim:int
        The dimension of the tensor.
        For example if the imput was 4 you would generate x, y, z, t,
        following classical cartesian nomenclature.

    Returns
    -------
    tuple[torch.Tensor, ...]
        A tuple of tensors of size dim
    """

    sampler = qmc.LatinHypercube(d=dim)
    lhs_samples = sampler.random(n_points)

    lhs_samples = torch.Tensor(lhs_samples)

    lhs_samples.requires_grad = True

    return tuple((lhs_samples[:, i].view(-1, 1)) for i in range(dim))


def pde_residual_1d(x: torch.Tensor,
                    t: torch.Tensor, model: nn.Module,
                    D: float = 0.1, R: float = 1) -> torch.Tensor:
    """
    Calculates the residual of the KPP-Fisher equation in 1D.

    Parameters
    ----------
    x:torch.Tensor
        The spatial coordinates
    t:torch.Tensor
        The temporal coordinates
    D:float=0.01
        The diffusion coefficient
    R:float=1
        The reaction rate

    Returns
    -------
    residual:torch.Tensor
        The residual of the KPP-Fisher equation
    """

    u = model(x, t)

    u_t = torch.autograd.grad(u, t, torch.ones_like(
        u), create_graph=True)[0]  # du/dt
    u_x = torch.autograd.grad(u, x, torch.ones_like(
        u), create_graph=True)[0]  # du/dx
    u_xx = torch.autograd.grad(u_x, x, torch.ones_like(
        u), create_graph=True)[0]  # d^2u/dx^2

    residual = u_t-D*u_xx-R*u*(1-u)
    return residual


def exact_solution_1D(x: torch.Tensor,
                      t: torch.Tensor,
                      D: float = 0.1,
                      R: float = 1) -> torch.Tensor:
    """
    Calculates the exact solution of the KPP-Fisher equation in 1D.

    Parameters
    ----------
    x:torch.Tensor
        The spatial coordinates
    t:torch.Tensor
        The temporal coordinates
    D:float=0.01
        The diffusion coefficient
    R:float=1
        The reaction rate

    Returns
    -------
    exact_solution:torch.Tensor
        The exact solution of the KPP-Fisher equation in 1D
    """

    exponent = (((R/(2*D))**0.5)*(x-t*(2*R*D)**0.5))
    exp = torch.exp(exponent)
    exact_solution = 1/(1+exp)
    return exact_solution


def loss_function_1d(x: torch.Tensor,
                     t: torch.Tensor,
                     model: nn.Module) -> float:
    """
    Computes the loss function as the sum of the initial conditions loss,
    boundary conditions loss and the residual loss.

    Parameters
    ----------
    x:torch.Tensor
        The spatial coordinates
    t:torch.Tensor
        The temporal coordinates
    model:nn.Module
        The approximated u(x,t)

    Returns
    -------
    loss:float
        The loss function
    """

    # initial condition loss
    u_pr = model(x, torch.zeros_like(x))
    u_ex = exact_solution_1D(x, torch.zeros_like(x))
    loss_ic = torch.mean((u_pr-u_ex)**2)

    # boundary condition loss
    u_0_pr = model(torch.zeros_like(t), t)
    u_0_ex = exact_solution_1D(torch.zeros_like(t), t)
    u_1_pr = model(torch.full_like(t, 1), t)
    u_1_ex = exact_solution_1D(torch.full_like(t, 1), t)
    loss_bc = torch.mean((u_0_pr-u_0_ex)**2)+torch.mean((u_1_pr-u_1_ex)**2)

    # residual loss
    loss_pde = torch.mean(pde_residual_1d(x, t, model)**2)

    # total loss
    return loss_bc+loss_ic+loss_pde


def training_loop_1D(n_epochs: int, n_neurons: int,
                     n_points: int) -> tuple[nn.Module, list]:
    """
    Runs n_epochs loops to train the model as defined in pr_PINN_1d

    Parameters
    ----------
    n_epochs:int
    The number of epochs for the training loop.
    n_neurons:int
    The numer of neurons per layer.
    n_points:int
    The number of points for LHS sampling.

    Returns
    -------
    model:nn.Module
    The trained PINN.
    loss_list:list
    A list containing the loss every 10 epochs.
    """

    model = PINN_1d(n_neurons)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    model.apply(lambda m: m.reset_parameters()
                # reinitialize the model
                if hasattr(m, 'reset_parameters') else None)

    # generating training points
    x, t = lhs_sample_generator(n_points, 2)
    loss_list = []

    for epoch in range(n_epochs):
        model.train()
        loss = loss_function_1d(x, t, model)
        if epoch % 10 == 0:
            loss_list.append([loss.item(), epoch])
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    return model, loss_list


def generate_plot_1d(n_epocs: int, n_neurons: int, n_points: int) -> Figure:
    """
    Runs the loop and then generates a side by side contour
    plot of the correct solution and the one obtained by the PINN
    and a plot of the loss related to the epochs.

    Parameters
    ----------
    n_epochs:int
    The number of epochs for the loop
    n_neurons:int
    The numer of neurons per layer.
    n_points:int
    The number of points for LHS sampling.

    Returns
    -------
    fig:Figure
    Returns the figure for gradio to show.
    """

    model, loss_list = training_loop_1D(n_epocs, n_neurons, n_points)

    x_test = torch.linspace(0, 1, 100).view(-1, 1)
    t_test = torch.linspace(0, 1, 100).view(-1, 1)
    x_test, t_test = torch.meshgrid(
        x_test.squeeze(), t_test.squeeze(), indexing='xy')
    x_test = x_test.reshape(-1, 1)
    t_test = t_test.reshape(-1, 1)

    model.eval()
    with torch.no_grad():
        u_pred = model(x_test, t_test).numpy()
        u_exact = exact_solution_1D(x_test, t_test).numpy()

    losses = [item[0] for item in loss_list]
    epochs = [item[1] for item in loss_list]

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(10, 4))

    x_test = x_test.numpy().reshape(100, 100)
    t_test = t_test.numpy().reshape(100, 100)
    u_pred = u_pred.reshape(100, 100)
    u_exact = u_exact.reshape(100, 100)

    c1 = ax1.contourf(x_test, t_test, u_pred, levels=250, cmap='jet')
    fig.colorbar(c1, ax=ax1)
    c2 = ax2.contourf(x_test, t_test, u_exact, levels=250, cmap='jet')
    fig.colorbar(c2, ax=ax2)
    ax3.plot(epochs, losses, label="loss")
    ax3.set_yscale('log')
    ax3.set_xlabel('epoch')
    ax3.set_ylabel('loss')
    ax3.grid(True)
    plt.tight_layout()

    return fig
